version: '1.0'
services:
  social-network:
    container_name: social-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: social-network
      POSTGRES_PASSWORD: social-network
      POSTGRES_DB: social-network
    ports:
      - "5432:5432"