version: '3'

services:
  social-network:
    container_name: social-network
    image: skillboxgroup46/social-network:v1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/social-network
      MAIL: "timullkaebay@gmail.com"
      PASSWORD_MAIL: "qxux ibsj uhsn jnio"
      ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
      ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
      REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
      REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
      ENABLE_MS_NOTIFICATIONS: true
      NOTIFICATIONS_API_URL: "ms-notifications:8088"
    depends_on:
      - db

  ms-notifications:
    container_name: ms-notifications
    image: skillboxgroup46/ms-notifications:v1.0.0
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/social-network
      MAIL: "timullkaebay@gmail.com"
      PASSWORD_MAIL: "qxux ibsj uhsn jnio"
      ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
      ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
      REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
      REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"
      FRIEND_API_URL: "social-network:8080"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: social-network
      POSTGRES_PASSWORD: social-network
      POSTGRES_DB: social-network
    ports:
      - "5432:5432"

  zookeeper:
    image: ubuntu/zookeeper:edge
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
