version: '3.8'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: social-network
      POSTGRES_PASSWORD: social-network
      POSTGRES_DB: social-network
    ports:
      - "5432:5432"