server:
  port: 8080

spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-social.network-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/social-network
    username: social-network
    password: social-network
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        default_schema: public
    open-in-view: false

captcha:
  expiration: 5m

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
