server:
  port: 8080

spring:
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${PASSWORD_MAIL}
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: true
    drop-first: false
  #    default-schema: social-network
  #    liquibase-schema: social-network
  datasource:
    url: jdbc:postgresql://localhost:5432/social-network
    username: social-network
    password: social-network
    driverClassName: org.postgresql.Driver

access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"